[package]
name = "plug"
version = "0.1.0"
edition = "2024"


[dependencies]
keep = { version = "0.1.0", path = "../keep" }
plugmap = { version = "0.1.0", path = "../plugmap" }
proc_layer = {path = "proc_layer", optional=true}


[features]
default = ["macro"]
macro = ["dep:proc_layer"]
